
build:
  image: docker:stable
  services:
  - docker:dind
  stage: build
  script:
  - mkdir dist
  - echo $TOOLBOX_APPKEYS > resources/toolbox.appkeys
  - docker build -t toolbox .
  - docker run -e CI_PIPELINE_IID=$CI_PIPELINE_IID -e CI_BUILD_REF=$CI_BUILD_REF -e CI_JOB_ID=$CI_JOB_ID -e TOOLBOX_BUILDERKEY=$BUILDER_KEY -v $PWD/dist:/dist --rm toolbox
  artifacts:
    paths:
    - $PWD/dist
