version: '3'
services:
  app:
    build:
      context: .
    command: ./build.sh
    volumes:
      - .:/app
      - /tmp/dist:/dist
    ports:
      - 2345:2345
    security_opt:
      - seccomp:unconfined
