version: 2
jobs:
  prep:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/watermint/toolbox
    steps:
      - checkout
      - run: echo "$TOOLBOX_APPKEYS" > resources/toolbox.appkeys
      - run: go get github.com/Masterminds/glide
      - run: go get github.com/GeertJohan/go.rice
      - run: go get github.com/GeertJohan/go.rice/rice
      - run: go get golang.org/x/tools/cmd/cover
      - run: go get github.com/modocache/gover
      - run: go get github.com/mattn/goveralls
      - run: glide install
      - save_cache:
          - key: tbx-{{ .Environment.CIRCLE_SHA1 }}
          - paths:
              - ~/tbx-build

  test:
    docker:
      - image: circleci/golang:1.12
    steps:
      - restore_cache:
          -  tbx-{{ .Environment.CIRCLE_SHA1 }}
      - run: go list -f '{{if len .TestGoFiles}}"go test -coverprofile={{.Dir}}/.coverprofile {{.ImportPath}}"{{end}}' $(glide novendor) | xargs -L 1 sh -c
      - run: gover
      - run: goveralls -coverprofile=gover.coverprofile -service=circle-ci -v
      - run: ./build.sh
      - store_artifacts:
          path: /go/src/github.com/watermint/toolbox/dist
