version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/watermint/toolbox
    steps:
      - checkout
      - run: ./.circleci/prepare.sh
      - run: go get github.com/Masterminds/glide
      - run: go get github.com/GeertJohan/go.rice
      - run: go get github.com/GeertJohan/go.rice/rice
      - run: go get golang.org/x/tools/cmd/cover
      - run: go get github.com/modocache/gover
      - run: go get github.com/mattn/goveralls
      - run: glide install
      - run: go list -f '{{if len .TestGoFiles}}"go test -coverprofile={{.Dir}}/.coverprofile {{.ImportPath}}"{{end}}' $(glide novendor) | xargs -L 1 sh -c
      - run: gover
      - run: goveralls -coverprofile=gover.coverprofile -service=circle-ci -v
      - run: ./build.sh
      - run: go run tbx.go file upload -peer end_to_end_test -dropbox-path /watermint-toolbox-build -local-path /go/src/github.com/watermint/toolbox/dist
      - store_artifacts:
          path: /go/src/github.com/watermint/toolbox/dist
