version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/watermint/toolbox
    steps:
      - checkout
      - run: shasum -a 256 go.mod > go.mod.sum
      - restore_cache:
          key: go-pkg-mod-{{ checksum "go.mod.sum" }}
      - run: ./.circleci/prepare.sh
      - run: go get github.com/GeertJohan/go.rice
      - run: go get github.com/GeertJohan/go.rice/rice
      - run: ./build.sh
      - store_artifacts:
          path: /go/src/github.com/watermint/toolbox/dist

  test:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/watermint/toolbox
    steps:
      - checkout
      - run: shasum -a 256 go.mod > go.mod.sum
      - restore_cache:
          key: go-pkg-mod-{{ checksum "go.mod.sum" }}
      - run: ./.circleci/prepare.sh
      - run: mkdir -p test/results
      - run: go get github.com/GeertJohan/go.rice
      - run: go get github.com/GeertJohan/go.rice/rice
      - run: go get golang.org/x/tools/cmd/cover
      - run: go get github.com/mattn/goveralls
      - run: go get github.com/jstemmer/go-junit-report
      - run: CGO_ENABLED=0 go test -short -v -p 1 -coverprofile=.coverprofile ./... 2>&1 | go-junit-report > test/results/all.xml
      - save_cache:
          key: go-pkg-mod-{{ checksum "go.mod.sum" }}
          paths:
            - /go/pkg/mod
      - store_test_results:
          path: /go/src/github.com/watermint/toolbox/test/results
      - run: goveralls -coverprofile=.coverprofile -service=circle-ci -v

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test