version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/watermint/toolbox
    steps:
      - checkout
      - restore_cache:
          key: go-pkg-mod-{{ checksum "go.mod" }}
      - run: ./.circleci/prepare.sh
      - run: go get github.com/GeertJohan/go.rice
      - run: go get github.com/GeertJohan/go.rice/rice
      - run: ./build.sh
      - run: go run tbx.go dev ci artifact up -dropbox-path /watermint-toolbox-build -local-path /go/src/github.com/watermint/toolbox/dist
      - store_artifacts:
          path: /go/src/github.com/watermint/toolbox/dist

  test:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/watermint/toolbox
    steps:
      - checkout
      - restore_cache:
          key: go-pkg-mod-{{ checksum "go.mod" }}
      - run: ./.circleci/prepare.sh
      - run: mkdir -p test/results
      - run: go get github.com/GeertJohan/go.rice
      - run: go get github.com/GeertJohan/go.rice/rice
      - run: go get golang.org/x/tools/cmd/cover
      - run: go get github.com/mattn/goveralls
      - run: go get github.com/jstemmer/go-junit-report
      - run: CGO_ENABLED=0 go test -p 1 -coverprofile=.coverprofile ./... 2>&1 | tee test/results/all.txt
      - run: cat test/results/all.txt | go-junit-report > test/results/all.xml
      - run: cat test/restuls/all.xml
      - save_cache:
          key: go-pkg-mod-{{ checksum "go.mod" }}
          paths:
            - /go/pkg/mod
      - store_test_results:
          path: /go/src/github.com/watermint/toolbox/test/results
      - run: goveralls -coverprofile=.coverprofile -service=circle-ci -v

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test