version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/watermint/toolbox
    steps:
      - checkout
      - run: mkdir -p $HOME/.toolbox/secrets
      - run: echo "$TOOLBOX_APPKEYS" > resources/toolbox.appkeys
      - run: echo "$TOOLBOX_ENDTOEND" > $HOME/.toolbox/secrets/6600b0a53d04619d6b05ff732d085379de327fc52ba2283ae91d0fd9.tokens
      - run: go get github.com/Masterminds/glide
      - run: go get github.com/GeertJohan/go.rice
      - run: go get github.com/GeertJohan/go.rice/rice
      - run: go get golang.org/x/tools/cmd/cover
      - run: go get github.com/modocache/gover
      - run: go get github.com/mattn/goveralls
      - run: glide install
      - run: go list -f '{{if len .TestGoFiles}}"go test -coverprofile={{.Dir}}/.coverprofile {{.ImportPath}}"{{end}}' $(glide novendor) | xargs -L 1 sh -c
      - run: gover
      - run: goveralls -coverprofile=gover.coverprofile -service=circle-ci -v
      - run: ./build.sh
      - store_artifacts:
          path: /go/src/github.com/watermint/toolbox/dist
